apiVersion: v1
kind: ResourceQuota
metadata:
  name: vitalbridge-quota
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vitalbridge.labels" . | nindent 4 }}
spec:
  hard:
    pods: "30"
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "12"
    limits.memory: 12Gi
    persistentvolumeclaims: "5"
    requests.storage: "50Gi"
    services: "10"
    secrets: "15"
    configmaps: "15"
